version: '3.0'
services:
  node-red:
    build: .
    ports:
      - 1880:1880
    volumes:
      - ./app:/data
    labels:
      - "traefik.enable=true"
      - "traefik.web.frontend.rule=Host:quiz.snek.pw"